src/Transporter.WebMvc/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Diagnostics;
using System.Security.Claims;
using System.Threading.Tasks;
using Transporter.Administration.Application.Service;
using Transporter.Administration.Application.ViewModels;
using Transporter.WebMvc.Models;

namespace Transporter.WebMvc.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserAppService _userAppService;

        public LoginController(IUserAppService userAppService)
        {
            _userAppService = userAppService;
        }

        public async Task<IActionResult> Index()
        {
            await HttpContext.SignOutAsync();

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel loginViewModel)
        {
            var user = _userAppService.FindUserByUserName(loginViewModel.UserName);

            if (user != null && user.Password.Equals(loginViewModel.Password))
            {
                var claims = new List<Claim>
                {
                    new Claim("UserId", user.Id.ToString())
                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                ViewBag.TheResult = true;
                return RedirectToAction("Index", "Home");
            }

            ViewBag.TheResult = false;
            return View("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Transporter.WebMvc/Controllers/TransportRecordController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using Transporter.Administration.Application.Service;
using Transporter.Transport.Application.Service;
using Transporter.Transport.Application.ViewModels;

namespace Transporter.WebMvc.Controllers
{
    [Authorize]
    public class TransportRecordController : Controller
    {
        private readonly ITransportAppService _transportAppService;
        private readonly IUserAppService _userAppService;

        public TransportRecordController(ITransportAppService vehicleAppService, IUserAppService userAppService)
        {
            _transportAppService = vehicleAppService;
            _userAppService = userAppService;
        }

        public IActionResult CreateTransportRecord()
        {
            return View();
        }

        public IActionResult IndexReport()
        {
            var dados = _transportAppService.MakeReport(DateTime.MinValue, DateTime.MinValue);

            return View("IndexReport", dados);
        }

        [HttpPost]
        public IActionResult GetReport(DateTime dateStart, DateTime dateEnd)
        {
            var dados = _transportAppService.MakeReport(dateStart, dateEnd);

            return PartialView("GetReport", dados);
        }

        [HttpPost]
        public async Task<IActionResult> RegisterTransportRecord(TransportRecordViewModel transportRecordViewModel)
        {
            var vehicle = _transportAppService.FindVehicleByLicensePlate(transportRecordViewModel.LicensePlate);

            if (vehicle == null)
            {
                ViewBag.TheResult = false;
                ViewBag.MsgResult = "Placa do veículo não cadastrada.";
                return View("CreateTransportRecord");
            }

            var person = _userAppService.FindPersonByCpf(transportRecordViewModel.CpfPassenger);
            if (person == null)
            {
                ViewBag.TheResult = false;
                ViewBag.MsgResult = "Cpf não cadastrado.";
                return View("CreateTransportRecord");
            }

            var personIsPassenger = _userAppService.FindPassengerByPersonId(person.Id) != null;

            if (!personIsPassenger)
            {
                ViewBag.TheResult = false;
                ViewBag.MsgResult = "O CPF informado não é de um passageiro.";
                return View("CreateTransportRecord");
            }

            ViewBag.TheResult = true;
            transportRecordViewModel.VehicleId = vehicle.Id;
            await _transportAppService.AddTransportRecord(transportRecordViewModel);

            return View("CreateTransportRecord");
        }
    }
}

src/Transporter.WebMvc/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Transporter.Administration.Application.Service;
using Transporter.Administration.Application.ViewModels;

namespace Transporter.WebMvc.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserAppService _userAppService;

        public UserController(IUserAppService userAppService)
        {
            _userAppService = userAppService;
        }

        public IActionResult CreateUser()
        {
            return View();
        }

        public IActionResult CreatePassenger()
        {
            return View();
        }

        public IActionResult CreateDriver()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> RegisterUser(UserViewModel userViewModel)
        {
            var cpfInUse = _userAppService.FindPersonByCpf(userViewModel.CPF) != null;

            if (cpfInUse)
            {
                ViewBag.TheResult = false;
                ViewBag.MsgResult = "Cpf já cadastrado.";
                return View("CreateUser");
            }

            await _userAppService.AddUser(userViewModel);
            ViewBag.TheResult = true;

            return View("CreateUser");
        }

        [HttpPost]
        public async Task<IActionResult> RegisterPassenger(PassengerViewModel passengerViewModel)
        {
            var cpfInUse = _userAppService.FindPersonByCpf(passengerViewModel.CPF) != null;

            if (cpfInUse)
            {
                ViewBag.TheResult = false;
                ViewBag.MsgResult = "Cpf já cadastrado.";
                return View("CreatePassenger");
            }

            await _userAppService.AddPassenger(passengerViewModel);
            ViewBag.TheResult = true;

            return View("CreatePassenger");
        }

        [HttpPost]
        public async Task<IActionResult> RegisterDriver(DriverViewModel driverViewModel)
        {
            var cpfInUse = _userAppService.FindPersonByCpf(driverViewModel.CPF) != null;

            if (cpfInUse)
            {
                ViewBag.TheResult = false;
                ViewBag.MsgResult = "Cpf já cadastrado.";
                return View("CreateDriver");
            }

            await _userAppService.AddDriver(driverViewModel);
            ViewBag.TheResult = true;

            return View("CreateDriver");
        }
    }
}

src/Transporter.WebMvc/Controllers/VehicleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Transporter.Administration.Application.Service;
using Transporter.Transport.Application.Service;
using Transporter.Transport.Application.ViewModels;

namespace Transporter.WebMvc.Controllers
{
    [Authorize]
    public class VehicleController : Controller
    {
        private readonly ITransportAppService _vehicleAppService;
        private readonly IUserAppService _userAppService;

        public VehicleController(ITransportAppService vehicleAppService, IUserAppService userAppService)
        {
            _vehicleAppService = vehicleAppService;
            _userAppService = userAppService;
        }

        public IActionResult CreateVehicle()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> RegisterVehicle(VehicleViewModel vehicleViewModel)
        {
            var licensePlateInUse = _vehicleAppService.FindVehicleByLicensePlate(vehicleViewModel.LicensePlate) != null;

            if (licensePlateInUse)
            {
                ViewBag.TheResult = false;
                ViewBag.MsgResult = "Placa do veículo já cadastrada.";
                return View("CreateVehicle");
            }

            var person = _userAppService.FindPersonByCpf(vehicleViewModel.CpfDriver);
            if (person == null)
            {
                ViewBag.TheResult = false;
                ViewBag.MsgResult = "Cpf não cadastrado.";
                return View("CreateVehicle");
            }

            var personIsDriver = _userAppService.FindDriverByPersonId(person.Id) != null;

            if (!personIsDriver)
            {
                ViewBag.TheResult = false;
                ViewBag.MsgResult = "O CPF informado não é de um motorista.";
                return View("CreateVehicle");
            }

            ViewBag.TheResult = true;
            await _vehicleAppService.AddVehicle(vehicleViewModel);

            return View("CreateVehicle");
        }
    }
}

src/Transporter.WebMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Transporter</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @if (User.Identity.IsAuthenticated)
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                }
                else
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Login" asp-action="Index">Transporter</a>
                }

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                @if (User.Identity.IsAuthenticated)
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="CreatePassenger">Cadastrar Passageiro</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="CreateDriver">Cadastrar Motorista</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vehicle" asp-action="CreateVehicle">Cadastrar Veículo</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="TransportRecord" asp-action="CreateTransportRecord">Registro de Transporte</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="TransportRecord" asp-action="IndexReport">Relatório</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Logout</a>
                            </li>
                        </ul>
                    </div>
                }
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Transporter.WebMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>